modLoader="javafml" 
loaderVersion="[47,)"
license="GPLv3" 

[[mods]]
modId="epicscorch"
version="1.0.0"
displayName="Epic Scorch"
authors="FranWDev (Updated from bakdpotato11 & hd42)"
description='''
Unofficial update for Epic Scorch. 
Original mod by bakdpotato11. 
Based on animations/structure by hd42.
Updated to the latest epicfight version by FranWDev.
'''

[[dependencies.epicscorch]]
modId="forge"
mandatory=true
versionRange="[47.3.12,)"
ordering="NONE"
side="BOTH"

[[dependencies.epicscorch]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"
